apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
  # change the service type to LoadBalancer for Cloud environment    
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: queue
  ports:
    - name: http
      port: 8161
      # This is an endpoint for other services 
    - name: endpoint
      port: 61616
  # no longer needed for production deployment      
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  # This represent which pods represented by this Service
  selector:
    app: position-tracker
  ports:
    - name: http
      port: 8080
  type: ClusterIP  
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
  type: ClusterIP 